### PR TITLE
Migrate to swift 3.0

### PR DESCRIPTION
**Pull request by AF-cgi**
Update your podspec file and your project setup! Your example isn't migrated due to Nimble and Quick.

### CODE REVIEW

**Review by mtrubnikov — APPROVED** [review]
Works for me. Thank you for posting!

**Comment by patrickmontalto** [comment]
any update on this?

**Comment by brendensuarez** [comment]
@zacwest can your merge this?

**Comment by zacwest** [comment]
Thanks. This is now done in #8 (along with the tests, etc.).

**Pull request closed without merging**
